#!/bin/bash
echo "Starting all Lambda functions import process..."
# Import all Lambda functions
terraform import "module.lambda_functions.aws_lambda_function.this[\"channel_restore_node\"]" one-journey-genai-channelRestoreNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"core_heap_node\"]" one-journey-genai-coreHeapNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"channel_switch_node\"]" one-journey-genai-channelSwitchNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"kcrm_enqueue_voice_node\"]" one-journey-genai-kcrmEnqueueVoiceNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"telegram_webhook\"]" one-journey-genai-telegramWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"core_set_choice_node\"]" one-journey-genai-coreSetChoiceNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"stt_webhook_node\"]" one-journey-genai-sttWebhookNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"rule_choice_node\"]" one-journey-genai-ruleChoiceNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"email_node\"]" one-journey-genai-emailNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"manage_file_storage\"]" one-journey-genai-manageFileStorage
terraform import "module.lambda_functions.aws_lambda_function.this[\"google_drive_webhook\"]" one-journey-genai-googleDriveWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"option_gateway\"]" one-journey-genai-optionGateway
terraform import "module.lambda_functions.aws_lambda_function.this[\"message_handler\"]" one-journey-genai-messageHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"call_workflow_node\"]" one-journey-genai-callWorkflowNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"core_gds_event\"]" one-journey-genai-coreGDSEvent
terraform import "module.lambda_functions.aws_lambda_function.this[\"pipeline_notification_node\"]" one-journey-genai-pipeLineNotificationNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"gds_webhook\"]" one-journey-genai-gdsWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"echo_whatsapp_node\"]" one-journey-genai-echoWhatsappNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"google_calendar_webhook\"]" one-journey-genai-googleCalendarWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"change_state\"]" one-journey-genai-changeState
terraform import "module.lambda_functions.aws_lambda_function.this[\"variable_node\"]" one-journey-genai-variableNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"request_node\"]" one-journey-genai-requestNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"disconnect_handler\"]" one-journey-genai-disconnectHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"customize_id_token\"]" one-journey-genai-customizeIDToken
terraform import "module.lambda_functions.aws_lambda_function.this[\"mass_creation\"]" one-journey-genai-massCreation
terraform import "module.lambda_functions.aws_lambda_function.this[\"error_catch_all\"]" one-journey-genai-errorCatchAll
terraform import "module.lambda_functions.aws_lambda_function.this[\"vonage_voice_webhook\"]" one-journey-genai-vonageVoiceWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"session_end\"]" one-journey-genai-sessionEnd
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_context\"]" one-journey-genai-executionContext
terraform import "module.lambda_functions.aws_lambda_function.this[\"process_transcription_node\"]" one-journey-genai-processTranscriptionNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"pipeline_response\"]" one-journey-genai-pipelineResponse
terraform import "module.lambda_functions.aws_lambda_function.this[\"reset_pswrd\"]" one-journey-genai-resetPswrd
terraform import "module.lambda_functions.aws_lambda_function.this[\"auth_handler\"]" one-journey-genai-authHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"telegram_webhook_bcg\"]" one-journey-genai-telegramWebhookBCG
terraform import "module.lambda_functions.aws_lambda_function.this[\"channel_hub_webhook\"]" one-journey-genai-channelHubWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"core_s3_event\"]" one-journey-genai-coreS3Event
terraform import "module.lambda_functions.aws_lambda_function.this[\"connect_handler\"]" one-journey-genai-connectHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"zendesk_webhook\"]" one-journey-genai-zendeskWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_patch\"]" one-journey-genai-executionPatch
terraform import "module.lambda_functions.aws_lambda_function.this[\"rule_gateway_node\"]" one-journey-genai-ruleGatewayNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"vonage_stream_webhook\"]" one-journey-genai-vonageStreamWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"webform_webhook\"]" one-journey-genai-webformWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_event\"]" one-journey-genai-executionEvent
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_continue\"]" one-journey-genai-executionContinue
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_stop\"]" one-journey-genai-executionStop
terraform import "module.lambda_functions.aws_lambda_function.this[\"talkjs_webhook\"]" one-journey-genai-talkJsWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"open_messaging_webhook\"]" one-journey-genai-openMessagingWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"for_each_node\"]" one-journey-genai-forEachNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"cognito_emails_customizer\"]" one-journey-genai-cognitoEmailsCustomizer
terraform import "module.lambda_functions.aws_lambda_function.this[\"error\"]" one-journey-genai-error
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_get\"]" one-journey-genai-executionGet
terraform import "module.lambda_functions.aws_lambda_function.this[\"zendesk_node\"]" one-journey-genai-zendeskNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"webform_get\"]" one-journey-genai-webformGet
terraform import "module.lambda_functions.aws_lambda_function.this[\"genesys_close_chat_node\"]" one-journey-genai-genesysCloseChatNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"step_function_delete\"]" one-journey-genai-stepFunctionDelete
terraform import "module.lambda_functions.aws_lambda_function.this[\"pre_sign_up\"]" one-journey-genai-preSignUp
terraform import "module.lambda_functions.aws_lambda_function.this[\"step_function_list\"]" one-journey-genai-stepFunctionList
terraform import "module.lambda_functions.aws_lambda_function.this[\"action_node\"]" one-journey-genai-actionNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"genesys_enqueue_chat_node\"]" one-journey-genai-genesysEnqueueChatNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"meta_node\"]" one-journey-genai-metaNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"manage_queue_channel\"]" one-journey-genai-manageQueueChannel
terraform import "module.lambda_functions.aws_lambda_function.this[\"azure_communication_webhook\"]" one-journey-genai-azureCommunicationWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"google_chat_webhook\"]" one-journey-genai-googleChatWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"costs\"]" one-journey-genai-costs
terraform import "module.lambda_functions.aws_lambda_function.this[\"hand_off_node\"]" one-journey-genai-handOffNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"authorizer\"]" one-journey-genai-authorizer
terraform import "module.lambda_functions.aws_lambda_function.this[\"tool_json_data_transform_node\"]" one-journey-genai-toolJSONDataTransformNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"tool_json_data_injection_node\"]" one-journey-genai-toolJSONDataInjectionNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"default_handler\"]" one-journey-genai-defaultHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"create_context_node\"]" one-journey-genai-createContextNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"user_me\"]" one-journey-genai-userMe
terraform import "module.lambda_functions.aws_lambda_function.this[\"core_batch\"]" one-journey-genai-coreBatch
terraform import "module.lambda_functions.aws_lambda_function.this[\"speech_to_text_node\"]" one-journey-genai-speechToTextNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"signalwire_webhook\"]" one-journey-genai-signalwireWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"whatsapp_webhook\"]" one-journey-genai-whatsappWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"vonage_streaming_handler\"]" one-journey-genai-vonageStreaminggHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"entity_gateway\"]" one-journey-genai-entityGateway
terraform import "module.lambda_functions.aws_lambda_function.this[\"debugs\"]" one-journey-genai-debugs
terraform import "module.lambda_functions.aws_lambda_function.this[\"execution_delete\"]" one-journey-genai-executionDelete
terraform import "module.lambda_functions.aws_lambda_function.this[\"generate_prompt_node\"]" one-journey-genai-generatePromptNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"publish_workflow_patch\"]" one-journey-genai-publishWorkflowPatch
terraform import "module.lambda_functions.aws_lambda_function.this[\"wapi_webhook\"]" one-journey-genai-wapiWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"pipeline_node\"]" one-journey-genai-pipelineNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"broadcast_handler\"]" one-journey-genai-broadcastHandler
terraform import "module.lambda_functions.aws_lambda_function.this[\"core_warm\"]" one-journey-genai-coreWarm
terraform import "module.lambda_functions.aws_lambda_function.this[\"transcribe_action_node\"]" one-journey-genai-transcribeActionNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"telnyx_stream_webhook\"]" one-journey-genai-telnyxStreamWebhook
terraform import "module.lambda_functions.aws_lambda_function.this[\"stop_workflow_node\"]" one-journey-genai-stopWorkflowNode
terraform import "module.lambda_functions.aws_lambda_function.this[\"check_connections_handler\"]" one-journey-genai-checkConnectionsHandler

echo "All Lambda functions imported successfully!"